PRAGMA foreign_keys=on;
PRAGMA encoding="UTF-8";
CREATE TABLE Countries(id integer not null primary key autoincrement, name text not null);
CREATE TABLE People(id integer not null primary key autoincrement, name text not null, date_of_birth integer);
CREATE TABLE Art_types(id integer not null primary key autoincrement, name text not null);
CREATE TABLE Cities(id integer not null primary key autoincrement, name text not null, country_id integer not null, foreign key (country_id) references Countries (id));
CREATE TABLE Museums(id integer not null primary key autoincrement, name text not null, date_found integer, city_id integer not null, foreign key (city_id) references Cities (id));
CREATE TABLE Artworks(id integer not null primary key autoincrement, name text not null, type_id integer not null, date_created integer, museum_id integer, foreign key (type_id) references Art_types (id), foreign key (museum_id) references Museums (id));
CREATE TABLE Arts_people(art_id integer not null, people_id integer not null, primary key (art_id, people_id), foreign key (art_id) references Artworks (id), foreign key (people_id) references People (id));
CREATE TABLE Country_person(country_id integer not null, people_id integer not null, primary key (country_id, people_id), foreign key (country_id) references Countries (id), foreign key (people_id) references People (id));
CREATE TABLE Deaths(people_id integer not null primary key, date integer not null, foreign key (people_id) references People (id));
